const blogPosts = [
    {
      href: "/blog/briefing-launch",
      image: "/images/blogVom Briefing zum Launch-the eksperts.svg",
      alt: "Vom Briefing zum Launch",
      title: "Vom Briefing zum Launch",
      readTime: "Lesedauer: ca. 4–5 Minuten",
      categories: ["Agentur & Zusammenarbeit "],
    },
    {
      href: "/blog/salesforce-berater-unterscheidung",
      image: "/images/Salesforce--Consultant.png",
      alt: "Was unterscheidet dich von anderen Salesforce Consultants?",
      title: "Was unterscheidet dich von anderen Salesforce Consultants?",
      readTime: "Lesedauer: ca. 3–4 Minuten",
      categories: [" Salesforce & CRM"],
    },
    {
      href: "/blog/der-start-deiner-salesforce-zertifizierungs-reise",
      image: "/images/Salesforce-Journe.png",
      alt: "Der Start deiner Salesforce-(Zertifizierung's)-Reise",
      title: "Der Start deiner Salesforce-(Zertifizierung's)-Reise",
      readTime: "Lesedauer: ca. 4–5 Minuten",
      categories: [" Salesforce & CRM "],
    },
    {
      href: "/blog/agile-projektleitung",
      image: "/images/blogAgile Projektleitung-the eksperts.svg",
      alt: " Agile Projektleitung",
      title: " Agile Projektleitung",
      readTime: "Lesedauer: ca. 4–5 Minuten",
      categories: [, "Agentur & Zusammenarbeit "],
    },
    {
      href: "/blog/ai-projektmanagement",
      image: "/images/blogAI-Projektleitung-the eksperts.svg",
      alt: " AI-Projektmanagement ",
      title: " AI-Projektmanagement ",
      readTime: "Lesedauer: ca. 4–5 Minuten",
      categories: ["KI & Technologische Trends"],
    },
    {
      href: "/blog/der-unterschatzte-boost",
      image: "/images/blogDer unterschätzte Boost-the eksperts.svg",
      alt: "Der unterschätzte Boost",
      title: "Der unterschätzte Boost",
      readTime: "Lesedauer: ca. 2 Minuten",
      categories: ["Webdesign & User Experience (UX/UI)"],
    },
  
    {
      href: "/blog/website-erstellen-schweiz-guide",
      image: "/images/Blog1-the eksperts.svg",
      alt: "Der ultimative Guide: Website erstellen Schweiz – Ihr Sprungbrett zum Online-Erfolg",
      title: "Der ultimative Guide: Website erstellen Schweiz – Ihr Sprungbrett zum Online-Erfolg",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: [
        "Website Erstellung & Planung",
        "Business Strategie & Digitalisierung",
        "Webdesign & User Experience (UX/UI)",
        "SEO & Online Marketing",
        " Lokale Präsenz & Standorte",
      ],
    },
    {
      href: "/blog/website-kmu-schweiz-digital",
      image: "/images/blog2-the eksperts.svg",
      alt: "Website für KMU Schweiz: So stärken Sie Ihr kleines oder mittleres Unternehmen digital",
      title: "Website für KMU Schweiz: So stärken Sie Ihr kleines oder mittleres Unternehmen digital",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: [
        "Business Strategie & Digitalisierung",
        "SEO & Online Marketing",
        "Zielgruppen & Branchen",
        " Lokale Präsenz & Standorte",
      ],
    },
    {
      href: "/blog/website-kmu-schweiz-kosten",
      image: "/images/blog3-the eksperts.svg",
      alt: "Was kostet eine Website für ein KMU in der Schweiz? Transparenz und ROI",
      title: "Was kostet eine Website für ein KMU in der Schweiz? Transparenz und ROI",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: [
        " Website Erstellung & Planung",
        " Business Strategie & Digitalisierung",
        "SEO & Online Marketing",
        "Zielgruppen & Branchen",
      ],
    },
    {
      href: "/blog/website-selbst-oder-agentur",
      image: "/images/blog4-the eksperts.svg",
      alt: "Website selbst erstellen oder Agentur beauftragen? Der grosse Vergleich für Ihr Schweizer Business ",
      title: "Website selbst erstellen oder Agentur beauftragen? Der grosse Vergleich für Ihr Schweizer Business ",
      readTime: "Lesedauer: ca. 6 Minuten",
      categories: [
        "Website Erstellung & Planung",
        "Business Strategie & Digitalisierung",
        " Webdesign & User Experience (UX/UI)",
        " SEO & Online Marketing",
        " Agentur & Zusammenarbeit ",
      ],
    },
    {
      href: "/blog/wordpress-website-schweiz",
      image: "/images/blog5-the eksperts.svg",
      alt: "WordPress Website Schweiz: Warum die meistgenutzte Plattform auch für Sie die Richtige sein könnte",
      title: "WordPress Website Schweiz: Warum die meistgenutzte Plattform auch für Sie die Richtige sein könnte",
      readTime: "Lesedauer: ca. 2 Minuten",
      categories: ["CMS & Plattformen", "SEO & Online Marketing"],
    },
    {
      href: "/blog/website-baukaesten-schweiz",
      image: "/images/blog6-the-eksperts.svg",
      alt: "Wix, Jimdo, Editor X & Co.: Website Baukästen für Einsteiger – Was geht, was nicht?",
      title: "Wix, Jimdo, Editor X & Co.: Website Baukästen für Einsteiger – Was geht, was nicht?",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: [
        "Website Erstellung & Planung",
        "CMS & Plattformen",
        " SEO & Online Marketing",
        "Zielgruppen & Branchen",
      ],
    },
    {
      href: "/blog/webagentur-digitalagentur-st-gallen-ostschweiz",
      image: "/images/blog7-the-eksperts.svg",
      alt: "Webagentur und Digitalagentur St. Gallen: Ihr digitaler Partner im Herzen der Ostschweiz ",
      title: "Webagentur und Digitalagentur St. Gallen: Ihr digitaler Partner im Herzen der Ostschweiz",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: ["  Lokale Präsenz & Standorte", ""],
    },
    {
      href: "/blog/website-coiffeur-friseur-schweiz",
      image: "/images/blog8-the eksperts.svg",
      alt: "Website für Coiffeur / Friseur: So gewinnen Sie online neue Kunden in der Schweiz",
      title: "Website für Coiffeur / Friseur: So gewinnen Sie online neue Kunden in der Schweiz",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: ["Zielgruppen & Branchen"],
    },
    {
      href: "/blog/moderne-business-website-design-trends",
      image: "/images/blog9-the eksperts.svg",
      alt: "Moderne Business-Website: Design-Trends, die Ihr Schweizer Unternehmen 2025 braucht",
      title: "Moderne Business-Website: Design-Trends, die Ihr Schweizer Unternehmen 2025 braucht",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: ["Webdesign & User Experience (UX/UI)"],
    },
    {
      href: "/blog/responsive-webdesign-schweiz",
      image: "/images/blog10-the eksperts.svg",
      alt: "Responsive Webdesign Schweiz: Warum Ihre Website auf jedem Gerät perfekt aussehen muss",
      title: "Responsive Webdesign Schweiz: Warum Ihre Website auf jedem Gerät perfekt aussehen muss",
      readTime: "Lesedauer: ca. 3 Minuten",
      categories: ["Webdesign & User Experience (UX/UI)"],
    },
    {
      href: "/blog/mobile-first-website-schweiz",
      image: "/images/blog11-the eksperts.svg",
      alt: "Mobile First Website Schweiz: Der Schlüssel zum Erfolg im Zeitalter des Smartphones",
      title: "Mobile First Website Schweiz: Der Schlüssel zum Erfolg im Zeitalter des Smartphones",
      readTime: "Lesedauer: ca. 3 Minuten",
      categories: ["Webdesign & User Experience (UX/UI)"],
    },
    {
      href: "/blog/ux-ui-design-website-kundenbindung",
      image: "/images/blog12-the eksperts.svg",
      alt: "UX/UI Design Website: Wie eine gute User Experience Ihre Kunden bindet",
      title: "UX/UI Design Website: Wie eine gute User Experience Ihre Kunden bindet",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: ["Webdesign & User Experience (UX/UI)"],
    },
    {
      href: "/blog/landing-page-erstellen-schweiz",
      image: "/images/blog13-the eksperts.svg",
      alt: "Landing Page erstellen Schweiz: So generieren Sie mehr Leads und Verkäufe",
      title: "Landing Page erstellen Schweiz: So generieren Sie mehr Leads und Verkäufe",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: ["Website Erstellung & Planung"],
    },
    {
      href: "/blog/onepager-freelancer-schweiz",
      image: "/images/blog14-the eksperts.svg",
      alt: "Onepager für Freelancer und Selbständige: Minimalistisch und doch wirkungsvoll",
      title: "Onepager für Freelancer und Selbständige: Minimalistisch und doch wirkungsvoll",
      readTime: "Lesedauer: ca. 3 Minuten",
      categories: ["Website Erstellung & Planung", "Zielgruppen & Branchen"],
    },
    {
      href: "/blog/website-anwaelte-zahnaerzte-architekten",
      image: "/images/blog15-the eksperts.svg",
      alt: "Branchenfokus: Ihre Website als digitaler Anker für Anwälte, Zahnärzte & Architekten in der Schweiz",
      title: "Branchenfokus: Ihre Website als digitaler Anker für Anwälte, Zahnärzte & Architekten in der Schweiz",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: ["Zielgruppen & Branchen"],
    },
    {
      href: "/blog/digitalagentur-zuerich-wirtschaft ",
      image: "/images/blog16-the-eksperts.svg",
      alt: "Digitalagentur Zürich: Ihr Wegbereiter im Zentrum der Schweizer Wirtschaft & Technologie",
      title:
        "Digitalagentur Zürich: Ihr Wegbereiter im Zentrum der Schweizer Wirtschaft & Technologie",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: [" Lokale Präsenz & Standorte"],
    },
    {
      href: "/blog/seo-website-erstellen-schweiz",
      image: "/images/blog17-the eksperts.svg",
      alt: "SEO-optimierte Website erstellen lassen: Ihr Weg zu mehr Sichtbarkeit in der Schweiz",
      title: "SEO-optimierte Website erstellen lassen: Ihr Weg zu mehr Sichtbarkeit in der Schweiz",
      readTime: "Lesedauer: ca. 5 Minuten",
      categories: ["SEO & Online Marketing"],
    },
    {
      href: "/blog/website-selbststaendige-schweiz",
      image: "/images/blog18-the eksperts.svg",
      alt: " Website für Selbständige: Ihr persönlicher Online-Auftritt, der überzeugt",
      title: " Website für Selbständige: Ihr persönlicher Online-Auftritt, der überzeugt",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: [
        "Business Strategie & Digitalisierung",
        "Zielgruppen & Branchen",
      ],
    },
    {
      href: "/blog/website-relaunch-agentur-schweiz",
      image: "/images/blog19-the eksperts.svg",
      alt: "Website-Relaunch Agentur Schweiz: Frischer Wind für Ihre bestehende Online-Präsenz",
      title: "Website-Relaunch Agentur Schweiz: Frischer Wind für Ihre bestehende Online-Präsenz",
      readTime: "Lesedauer: ca. 4 Minuten",
      categories: ["Website Erstellung & Planung", "Agentur & Zusammenarbeit "],
    },
    {
      href: "/blog/jetzt-website-erstellen-schweiz",
      image: "/images/blog20-the eksperts.svg",
      alt: " Jetzt Website erstellen lassen: Warum The Eksperts Ihr idealer Partner in der Schweiz ist",
      title: " Jetzt Website erstellen lassen: Warum The Eksperts Ihr idealer Partner in der Schweiz ist",
      readTime: "Lesedauer: ca. 3 Minuten",
      categories: ["Website Erstellung & Planung", "Agentur & Zusammenarbeit "],
    },
  ];
  export default blogPosts;
